# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a12tcpg238-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir d:/Work/GitLab/FPGA_lib/IP/VIP/clocked_video_input_ciris/syn/Vivado/cvi_ciris.cache/wt [current_project]
set_property parent.project_path d:/Work/GitLab/FPGA_lib/IP/VIP/clocked_video_input_ciris/syn/Vivado/cvi_ciris.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  d:/Work/GitLab/FPGA_lib/common/common_lib2/fifo/crs_lib_dc_fifo/rtl/crs_lib_dc_fifo.sv
  d:/Work/GitLab/FPGA_lib/common/common_lib2/ram/async_ram/rtl/crs_lib_async_ram.sv
  d:/Work/GitLab/FPGA_lib/IP/VIP/clocked_video_input_ciris/rtl/bt_to_avst.sv
  d:/Work/GitLab/FPGA_lib/IP/VIP/clocked_video_input_ciris/rtl/bt656_decoder.sv
  d:/Work/GitLab/FPGA_lib/IP/VIP/clocked_video_input_ciris/rtl/bt601_decoder.sv
  d:/Work/GitLab/FPGA_lib/IP/VIP/clocked_video_input_ciris/rtl/cvi_ciris.sv
}
set_property is_global_include true [get_files d:/Work/GitLab/FPGA_lib/common/common_lib2/fifo/crs_lib_dc_fifo/rtl/crs_lib_dc_fifo.sv]
set_property is_global_include true [get_files d:/Work/GitLab/FPGA_lib/common/common_lib2/ram/async_ram/rtl/crs_lib_async_ram.sv]
set_property is_global_include true [get_files d:/Work/GitLab/FPGA_lib/IP/VIP/clocked_video_input_ciris/rtl/bt_to_avst.sv]
set_property is_global_include true [get_files d:/Work/GitLab/FPGA_lib/IP/VIP/clocked_video_input_ciris/rtl/bt656_decoder.sv]
set_property is_global_include true [get_files d:/Work/GitLab/FPGA_lib/IP/VIP/clocked_video_input_ciris/rtl/bt601_decoder.sv]
set_property is_global_include true [get_files d:/Work/GitLab/FPGA_lib/IP/VIP/clocked_video_input_ciris/rtl/cvi_ciris.sv]
read_verilog -library xil_defaultlib {
  d:/Work/GitLab/FPGA_lib/common/common_lib/rtl/alt_vipvfr131_common_stream_output.v
  d:/Work/GitLab/FPGA_lib/common/common_lib/rtl/alt_vipvfr131_common_control_packet_encoder.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cvi_ciris -part xc7a12tcpg238-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cvi_ciris.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cvi_ciris_utilization_synth.rpt -pb cvi_ciris_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
