# TCL File Generated by Component Editor 18.1
# Sat Jan 21 19:57:42 MSK 2023
# DO NOT MODIFY


# 
# cvi_ciris "cvi_ciris" v1.0
# CIRIS 2023.01.21.19:57:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cvi_ciris
# 
set_module_property DESCRIPTION ""
set_module_property NAME cvi_ciris
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CIRIS/VIP
set_module_property AUTHOR CIRIS
set_module_property DISPLAY_NAME cvi_ciris
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cvi_ciris
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bt601_decoder.sv SYSTEM_VERILOG PATH rtl/bt601_decoder.sv
add_fileset_file bt_to_avst.sv SYSTEM_VERILOG PATH rtl/bt_to_avst.sv
add_fileset_file cvi_ciris.sv SYSTEM_VERILOG PATH rtl/cvi_ciris.sv TOP_LEVEL_FILE
add_fileset_file alt_vipvfr131_common_control_packet_encoder.v VERILOG PATH ../../../common/common_lib/rtl/alt_vipvfr131_common_control_packet_encoder.v
add_fileset_file alt_vipvfr131_common_stream_output.v VERILOG PATH ../../../common/common_lib/rtl/alt_vipvfr131_common_stream_output.v
add_fileset_file bt656_decoder.sv SYSTEM_VERILOG PATH rtl/bt656_decoder.sv
add_fileset_file crs_lib_async_ram.sv SYSTEM_VERILOG PATH ../../../common/common_lib2/ram/async_ram/rtl/crs_lib_async_ram.sv
add_fileset_file crs_lib_dc_fifo.sv SYSTEM_VERILOG PATH ../../../common/common_lib2/fifo/crs_lib_dc_fifo/rtl/crs_lib_dc_fifo.sv


# 
# parameters
# 
add_parameter BITS_PER_SYMBOL INTEGER 8
set_parameter_property BITS_PER_SYMBOL DEFAULT_VALUE 8
set_parameter_property BITS_PER_SYMBOL DISPLAY_NAME BITS_PER_SYMBOL
set_parameter_property BITS_PER_SYMBOL TYPE INTEGER
set_parameter_property BITS_PER_SYMBOL UNITS None
set_parameter_property BITS_PER_SYMBOL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITS_PER_SYMBOL HDL_PARAMETER true
add_parameter SYMBOLS_PER_BEAT INTEGER 1
set_parameter_property SYMBOLS_PER_BEAT DEFAULT_VALUE 1
set_parameter_property SYMBOLS_PER_BEAT DISPLAY_NAME SYMBOLS_PER_BEAT
set_parameter_property SYMBOLS_PER_BEAT TYPE INTEGER
set_parameter_property SYMBOLS_PER_BEAT UNITS None
set_parameter_property SYMBOLS_PER_BEAT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYMBOLS_PER_BEAT HDL_PARAMETER true
add_parameter HEIGHT INTEGER 480
set_parameter_property HEIGHT DEFAULT_VALUE 480
set_parameter_property HEIGHT DISPLAY_NAME HEIGHT
set_parameter_property HEIGHT TYPE INTEGER
set_parameter_property HEIGHT UNITS None
set_parameter_property HEIGHT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property HEIGHT HDL_PARAMETER true
add_parameter WIDTH INTEGER 640 ""
set_parameter_property WIDTH DEFAULT_VALUE 640
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH WIDTH ""
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH DESCRIPTION ""
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter SYNC_SIGNALS STRING Separate
set_parameter_property SYNC_SIGNALS DEFAULT_VALUE Separate
set_parameter_property SYNC_SIGNALS DISPLAY_NAME SYNC_SIGNALS
set_parameter_property SYNC_SIGNALS TYPE STRING
set_parameter_property SYNC_SIGNALS UNITS None
set_parameter_property SYNC_SIGNALS ALLOWED_RANGES {Separate Embedded}
set_parameter_property SYNC_SIGNALS HDL_PARAMETER true
add_parameter FAMILY STRING "Cyclone IV E"
set_parameter_property FAMILY DEFAULT_VALUE "Cyclone IV E"
set_parameter_property FAMILY DISPLAY_NAME FAMILY
set_parameter_property FAMILY TYPE STRING
set_parameter_property FAMILY UNITS None
set_parameter_property FAMILY HDL_PARAMETER true
add_parameter FIFO_NUMWORDS INTEGER 256 ""
set_parameter_property FIFO_NUMWORDS DEFAULT_VALUE 256
set_parameter_property FIFO_NUMWORDS DISPLAY_NAME FIFO_NUMWORDS
set_parameter_property FIFO_NUMWORDS WIDTH ""
set_parameter_property FIFO_NUMWORDS TYPE INTEGER
set_parameter_property FIFO_NUMWORDS UNITS None
set_parameter_property FIFO_NUMWORDS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_NUMWORDS DESCRIPTION ""
set_parameter_property FIFO_NUMWORDS HDL_PARAMETER true
add_parameter DEF_METASTAB STRING OFF
set_parameter_property DEF_METASTAB DEFAULT_VALUE OFF
set_parameter_property DEF_METASTAB DISPLAY_NAME DEF_METASTAB
set_parameter_property DEF_METASTAB TYPE STRING
set_parameter_property DEF_METASTAB UNITS None
set_parameter_property DEF_METASTAB ALLOWED_RANGES {OFF ON}
set_parameter_property DEF_METASTAB HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset_sink
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 1
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source dout_data data Output BITS_PER_SYMBOL*SYMBOLS_PER_BEAT
add_interface_port avalon_streaming_source dout_eop endofpacket Output 1
add_interface_port avalon_streaming_source dout_ready ready Input 1
add_interface_port avalon_streaming_source dout_sop startofpacket Output 1
add_interface_port avalon_streaming_source dout_valid valid Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point itu601_input
# 
add_interface itu601_input conduit end
set_interface_property itu601_input associatedClock clock
set_interface_property itu601_input associatedReset reset_sink
set_interface_property itu601_input ENABLED true
set_interface_property itu601_input EXPORT_OF ""
set_interface_property itu601_input PORT_NAME_MAP ""
set_interface_property itu601_input CMSIS_SVD_VARIABLES ""
set_interface_property itu601_input SVD_ADDRESS_GROUP ""

add_interface_port itu601_input h_sync_i h_sync Input 1
add_interface_port itu601_input v_sync_i v_sync Input 1
add_interface_port itu601_input itu_data_i itu_data Input BITS_PER_SYMBOL*SYMBOLS_PER_BEAT
add_interface_port itu601_input clk_itu_i clk_itu Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk_avalon_sv_i clk Input 1

