add_files -norecurse ../../../../../common/common_lib/rtl/alt_vipvfr131_common_control_packet_encoder.v; set_property IS_GLOBAL_INCLUDE 1 [get_files ../../../../../common/common_lib/rtl/alt_vipvfr131_common_control_packet_encoder.v]  
add_files -norecurse ../../../../../common/common_lib/rtl/alt_vipvfr131_common_stream_output.v; set_property IS_GLOBAL_INCLUDE 1 [get_files ../../../../../common/common_lib/rtl/alt_vipvfr131_common_stream_output.v]  
add_files -norecurse ../../rtl/bt656_decoder.sv; set_property IS_GLOBAL_INCLUDE 1 [get_files ../../rtl/bt656_decoder.sv]  
add_files -norecurse ../../../../../common/common_lib2/ram/async_ram/rtl/crs_lib_async_ram.sv; set_property IS_GLOBAL_INCLUDE 1 [get_files ../../../../../common/common_lib2/ram/async_ram/rtl/crs_lib_async_ram.sv]  
add_files -norecurse ../../rtl/bt_to_avst.sv; set_property IS_GLOBAL_INCLUDE 1 [get_files ../../rtl/bt_to_avst.sv]  
add_files -norecurse ../../../../../common/common_lib2/fifo/crs_lib_dc_fifo/rtl/crs_lib_dc_fifo.sv; set_property IS_GLOBAL_INCLUDE 1 [get_files ../../../../../common/common_lib2/fifo/crs_lib_dc_fifo/rtl/crs_lib_dc_fifo.sv]  
add_files -norecurse ../../rtl/bt601_decoder.sv; set_property IS_GLOBAL_INCLUDE 1 [get_files ../../rtl/bt601_decoder.sv]  
add_files -norecurse ../../rtl/cvi_ciris.sv; set_property IS_GLOBAL_INCLUDE 1 [get_files ../../rtl/cvi_ciris.sv]  
